name: main-workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: check out the source code
        uses: actions/checkout@v2
      
      - name: Setup go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.14"
          

      - name: print go version 
        run: go version

      - name:  name
        run: go test -v ./...