name: main-workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: check out the source code
        uses: actions/checkout@v2
      
      - name: Setup go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.14"
          

      - name: print go version 
        run: go version

      - name:  name
        run: go test -v ./...
        
      - name: Add public IP to AWS security group
        uses: andyfoston/aws-security-group-add-ip-action@support-aws-role
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-security-group-id: ${{ secrets.AWS_SECURITY_GROUP_ID }}
          port: '22'
          description: 'GitHub Action'
      
